[package]
name = "sheets-tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.19"
crossterm = "0.25"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
reqwest = "0.11"
tokio = { version = "1.22", features = [ "full" ] }
# Google sheets
google-sheets4 = "4"

